version: '0.1.4-beta-{build}'

platform: Any CPU
configuration: Release
os: Visual Studio 2019

before_build:
  - dotnet restore  
  - dotnet restore .\NetCoreTeamCity.Tests

build:
  parallel: true            
  project: NetCoreTeamCity.sln
  
after_build:
  - dotnet pack ".\NetCoreTeamCity\NetCoreTeamCity.csproj" -c Release -o artifacts
test_script:
  - dotnet test ".\NetCoreTeamCity.Tests\NetCoreTeamCity.Tests.csproj" -c Release --logger:trx;LogFileName=tests-results01.xml
  - ps: .\build\uploadtests.ps1 ".\NetCoreTeamCity.Tests\TestResults\tests-results01.xml"
artifacts:
  - path: artifacts\**\*.*
cache:
  - '%USERPROFILE%\.nuget\packages'
deploy:
  provider: NuGet
  api_key:
    secure: uqd0RkPv0vZ8gCfUD0MylWDv0kqJMGOq2GEfMyb4298a1O54we2pR3U0cNvtQMOr
  skip_symbols: false
  artifact: /.*\.nupkg/
